platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods'

target 'hotncold' do
  # Pods for hotncold
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'
  pod 'RNReanimated', :podspec => '../node_modules/react-native-reanimated/RNReanimated.podspec'
  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  use_unimodules!

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'react-native-mapbox-gl', :path => '../node_modules/@react-native-mapbox-gl/maps'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'



  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-ble-manager', :path => '../node_modules/react-native-ble-manager'

  pod 'react-native-bluetooth-status', :path => '../node_modules/react-native-bluetooth-status'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

end
